### ISSUE TITLE
Commenting feature doesn't seem to work

### ISSUE THREAD

**Issue by AntonNguyen** [reviewdog/action-golangci-lint#12]
The linter runs and finds issues, but it doesn't seem to actually comment on my pull request. Here's how my workflow is setup:
```yaml
name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: docker://reviewdog/action-golangci-lint:v1.0.3 # Pre-built image
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.github/.golangci.yml -v"
        env:
          GO111MODULE: on
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And here's my `.golangci.yml`:
```yaml
run:
  modules-download-mode: vendor

  skip-dirs:
    - gen$

  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  misspell:
    locale: US
  errcheck:
    check-type-assertions: false
    check-blank: false

linters:
  enable-all: true

issues:
  exclude-use-default: false
  max-same-issues: 0
```

Then here's the output of the action:
```bash
/usr/bin/docker run --name reviewdogactiongolangcilintv103_6740e8 --label 04bb81 --workdir /github/workspace --rm -e GO111MODULE -e REVIEWDOG_GITHUB_API_TOKEN -e INPUT_GITHUB_TOKEN -e INPUT_GOLANGCI_LINT_FLAGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/go-app/go-app":"/github/workspace" reviewdog/action-golangci-lint:v1.0.3
level=info msg="[config_reader] Used config file .github/.golangci.yml"
level=info msg="[lintersdb] Active 33 linters: [bodyclose deadcode depguard dupl errcheck funlen gochecknoglobals gochecknoinits goconst gocritic gocyclo gofmt goimports golint gosec gosimple govet ineffassign interfacer lll maligned misspell nakedret prealloc scopelint staticcheck structcheck stylecheck typecheck unconvert unparam unused varcheck]"
level=info msg="[lintersdb] Optimized sublinters [staticcheck gosimple unused stylecheck] into metalinter megacheck"
level=info msg="[loader] Go packages loading at mode 991 (imports|name|syntax|types|types_info|compiled_files|deps|types_sizes|files) took 1.379475969s"
level=info msg="[loader] SSA repr building timing: packages building 9.560552ms, total 127.168374ms"
level=info msg="[loader] Packages that do not compile: [github.com/ecobee/go-app/testdata]"
level=info msg="[runner] worker.1 took 21.074096ms with stages: unparam: 11.860542ms, dupl: 8.737957ms, gosec: 270.999µs, megacheck: 34.9µs, scopelint: 30.799µs, typecheck: 14.8µs, gocyclo: 14.3µs, prealloc: 13.7µs, errcheck: 10.4µs, funlen: 7.2µs, unconvert: 6.9µs, deadcode: 6.8µs, nakedret: 6.3µs, gochecknoglobals: 5.4µs, varcheck: 3.5µs, gofmt: 3.4µs, maligned: 2.3µs, ineffassign: 2.3µs, lll: 2.099µs, structcheck: 1.9µs, gochecknoinits: 1.8µs, goconst: 1.8µs"
level=info msg="[runner] worker.2 took 29.960253ms with stages: misspell: 21.372995ms, interfacer: 8.225859ms, gocritic: 194.699µs, govet: 95.4µs, golint: 15µs, depguard: 3.4µs, bodyclose: 2.8µs, goimports: 1.7µs"
level=info msg="[runner] Workers idle times: #1: 14.317829ms"
level=info msg="[runner] Issues before processing: 4, after processing: 2"
level=info msg="[runner] processing took 1.211594ms with stages: skip_files: 584.597µs, max_from_linter: 201.999µs, identifier_marker: 122.299µs, source_code: 106.1µs, skip_dirs: 54.299µs, nolint: 40.2µs, autogenerated_exclude: 29.5µs, filename_unadjuster: 28.6µs, cgo: 16.2µs, path_prettifier: 10.6µs, uniq_by_line: 8.9µs, path_shortener: 3.1µs, max_per_file_from_linter: 2.6µs, max_same_issues: 900ns, exclude: 700ns, diff: 600ns, exclude-rules: 400ns"
level=info msg="File cache stats: 2 entries of total size 308B"
level=info msg="Memory: 18 samples, avg is 120.6MB, max is 202.4MB"
level=info msg="Execution took 1.601896905s"
2019/09/25 11:20:13 [golangci-lint] reported: https://github.com/ecobee/go-app/runs/235583494
```

On the checks section, I do see 2 failures, but no in-line comments in the PR
<img width="584" alt="Screen Shot 2019-09-25 at 7 29 44 AM" src="https://user-images.githubusercontent.com/659985/65597096-55c2d180-df66-11e9-80a7-7f8aef5605fa.png">
