### ISSUE TITLE
502 Server Error

### ISSUE THREAD

**Issue by smutel** [reviewdog/action-golangci-lint#26]
Hello,

Currently I have this issue on my repo.
I don't understand where the error is.
Could you please help me understand this ?

https://github.com/smutel/terraform-provider-netbox/runs/571961907

```yml
Run reviewdog/action-golangci-lint@v1.1.3
  with:
    github_token: ***
    tool_name: golangci
    level: error
    reporter: github-pr-check
/usr/bin/docker run --name d00b33823f6f6ee2af4d7fb7d3ff1187414627_6d30ba --label d00b33 --workdir /github/workspace --rm -e INPUT_GITHUB_TOKEN -e INPUT_GOLANGCI_LINT_FLAGS -e INPUT_TOOL_NAME -e INPUT_LEVEL -e INPUT_REPORTER -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/terraform-provider-netbox/terraform-provider-netbox":"/github/workspace" d00b33:823f6f6ee2af4d7fb7d3ff1187414627
reviewdog: post failed for golangci: fail to parse diff: GET https://api.github.com/repos/smutel/terraform-provider-netbox/pulls/1: 502 Server Error []
```

Thanks.
