### ISSUE TITLE
Reviewdog crashes with error: `reviewdog: environment variable $REVIEWDOG_GITHUB_API_TOKEN is not set`

### ISSUE THREAD

**Issue by MarvinJWendt** [reviewdog/action-golangci-lint#556]
Reviewdog crashes with error: `reviewdog: environment variable $REVIEWDOG_GITHUB_API_TOKEN is not set`

Workflow:

```yml
name: Code analysis

on: [pull_request]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Linting with golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          reporter: github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.ACCESS_TOKEN }}
```

Action log: https://github.com/pterm/pterm/actions/runs/5423793140/jobs/9862524142?pr=507
