### ISSUE TITLE
on: [push] - reviewdog this is not a PullRequest build.

### ISSUE THREAD

**Issue by r10r** [reviewdog/action-golangci-lint#65]
Hi, how can this action be run on other events than  `pull_request`  ?

<img width="635" alt="Screenshot 2021-02-15 at 18 24 00" src="https://user-images.githubusercontent.com/309304/107977416-5d4fa400-6fbb-11eb-86b1-308ebc00f009.png">

```
Rubens-MBP:crc16 ruben$ cat .github/workflows/reviewdog.yaml 
name: reviewdog
on: [push, pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
```

**Comment by r10r** [comment]
Ok I found it myself. Need to set `reviewdog_flags: "--reporter=github-check"`

```yaml
name: reviewdog
on: [push, pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
          reviewdog_flags: "--reporter=github-check"
```
