### ISSUE TITLE
Can't use golangci-lint new-from-rev option

### ISSUE THREAD

**Issue by tinoquang** [reviewdog/action-golangci-lint#696]
I want to use the golangci-lint `new-from-rev` option ([details](https://golangci-lint.run/usage/configuration/#issues-configuration)). However, I encounter this issue
```
Run reviewdog/action-golangci-lint@v2
Installing Go ...
go env

🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
Installing golangci-lint ... https://github.com/golangci/golangci-lint
Restoring cache ...
Running golangci-lint ...
  /home/runner/work/_temp/reviewdog-0dbL9P/golangci-lint-1.58.1-linux-amd[64](https://github.com/PixoPH/pdax-imm-internal-market-making/actions/runs/9016044362/job/24771840077#step:3:66)/golangci-lint run --out-format line-number --config=.golangci-lint.yaml --new-from-rev=develop
  level=warning msg="The linter 'execinquery' is deprecated (since v1.58.0) due to: The repository of the linter has been archived by the owner. "
  level=warning msg="[runner] Can't process result by diff processor: can't prepare diff by revgrep: could not read git repo: error executing \"git diff --color=never --no-ext-diff --default-prefix --relative develop --\": exit status 128: fatal: bad revision 'develop'\n"
```

Here's my action file
```
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run lint check
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          golangci_lint_flags: "--config=.golangci-lint.yaml --new-from-rev=${{ github.base_ref }}"
```
Is there any suggestion to make it work? Thanks
