### ISSUE TITLE
v2.8.0 still using golangci-lint v1 linters-settings syntax for gofmt

### ISSUE THREAD

**Issue by reynoldsme** [reviewdog/action-golangci-lint#785]
After updating to [v2.8.0](https://github.com/reviewdog/action-golangci-lint/releases/tag/v2.8.0) of action-golangci-lint we are seeing the following output in our github actions:

```
Installing reviewdog ... https://github.com/reviewdog/reviewdog
  finding a release for latest
  downloading from https://github.com/reviewdog/reviewdog/releases/download/v0.20.3/reviewdog_0.20.3_Linux_x86_64.tar.gz
  extracting
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/reviewdog-uqaaFE -f /home/runner/work/_temp/c8d2586e-6a80-4422-9bbe-e16f91f8db66
Installing golangci-lint ... https://github.com/golangci/golangci-lint
  finding a release for latest
  downloading from https://github.com/golangci/golangci-lint/releases/download/v2.0.1/golangci-lint-2.0.1-linux-amd64.tar.gz
  extracting
  /usr/bin/tar xz --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/reviewdog-uqaaFE -f /home/runner/work/_temp/4e91139d-51b8-4c01-ac2a-b50c2e431e1f
Restoring cache ...
Running golangci-lint ...
  /home/runner/work/_temp/reviewdog-uqaaFE/golangci-lint-2.0.1-linux-amd64/golangci-lint run --output.text.path stdout --tests=false --timeout=5m
  Error: can't load config: gofmt is a formatter
  Failed executing command with error: can't load config: gofmt is a formatter
Error: Error: golangci-lint exited with status code: 3
```

Here is a truncated portion of our github action config:

```
name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golangci-lint:
    if: github.event_name == 'pull_request'
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Granting private modules access
        run: |
              .....
      - uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          level: "warning"
          reporter: github-pr-check
          golangci_lint_flags: "--tests=false --timeout=5m"
        env:
          GOPRIVATE: .....
```

It appears that action-golangci-lint is still using the golangci-lint v1 syntax for specifying gofmt as a formatter. https://golangci-lint.run/product/migration-guide/#linters-settings

Outside of `golangci_lint_flags: "--tests=false --timeout=5m"` I'm not aware that we are deviating from the defaults.
